### ISSUE TITLE
Any data transfer API for Rolling Spider

### ISSUE THREAD

**Issue by tony056** [Parrot-Developers/Samples#46]
Hi,
I would like to receive photos from my rolling spider, but I couldn't find any data transfer API for it.
The ftp method for data transfer is only for devices connected with wifi, right?

Thanks in advance!

**Comment by djavan-bertrand** [comment]
Hi, 
ARDataTransfer provides a way to get data transfer through ftp.

You can refer to [this code](https://github.com/ARDroneSDK3/Samples/issues/20#issuecomment-79106214) to get pictures from your Rolling, just change initWifiFtp by initBLEFtp.

Regards, 
Djavan

**Comment by astrodomi** [comment]
hi, sorry but I don't know how to call it in your example, can you help me please? 

            ftpError = ARUTILS_Manager_InitBLEFtp(_ftpListManager, ???, ???);

reference:
eARUTILS_ERROR ARUTILS_Manager_InitBLEFtp(ARUTILS_Manager_t *manager, ARUTILS_BLEDevice_t device, int port);

best regards.

**Comment by tony056** [comment]
yeah, I met the same problem as the above.
Could u give us an example of BLE ftp?
I think that will be very useful!

Thanks in advance!

**Comment by djavan-bertrand** [comment]
Hi, 

Based on [this conversation](https://github.com/ARDroneSDK3/Samples/issues/20#issuecomment-79106214), simply change the two ```ARUTILS_Manager_InitWifiFtp``` by : 
```objective-c
if(ftpError == ARUTILS_OK)
{
      ftpError = ARUTILS_Manager_InitBLEFtp(_ftpListManager, (__bridge ARUTILS_BLEDevice_t)((ARBLEService *)_service.service).peripheral, DEVICE_PORT);
}
        
if(ftpError == ARUTILS_OK)
{
      ftpError = ARUTILS_Manager_InitBLEFtp(_ftpQueueManager, (__bridge ARUTILS_BLEDevice_t)((ARBLEService *)_service.service).peripheral, DEVICE_PORT);
}
```
_service is the ARService used to connect to the RollingSpider (you can find _service in [the PilotingViewController class of the RollingSpiderPiloting sample](https://github.com/ARDroneSDK3/Samples/blob/master/iOS/RollingSpiderPiloting/RollingSpiderPiloting/RollingSpiderPiloting/PilotingViewController.h#L44) for example).

Hope this helps, 

Best regards, 
Djavan

**Comment by astrodomi** [comment]
thank you Djavan, 

 ARDATATRANSFER_MediasDownloader_New returned ARDATATRANSFER_OK but to my surprise the next step ARDATATRANSFER_MediasDownloader_GetAvailableMediasSync(_manager,0,&result); returned mediaListCount=0 and that is not true because there are photos in the internal memory, I tried different combinations of remoteDirectory "internal_000", "/internal_000/Rolling_Spider/media", and also looking at the sources in TestBLEFtp project I found different port numbers 21 and 51, why ? 
any help is appreciated, best regards

![screen shot 2015-05-13 at 13 21 40](https://cloud.githubusercontent.com/assets/10271636/7615359/a16dc910-f973-11e4-83fc-5a22baf36040.jpg)

**Comment by astrodomi** [comment]
any news with this problem ?

**Comment by SteBon90** [comment]
Hi, I have the same problem. 
https://github.com/Parrot-Developers/ARSDKBuildUtils/issues/59
