### ISSUE TITLE
linux compilation error - BebopDroneDecodeStream

### ISSUE THREAD

**Issue by alexcherpi** [Parrot-Developers/Samples#55]
Hi, when I compile 'BebopDecodeStream' I have an error:

alex@alexB083:~/Documents/SDKbebop/Samples/Unix/BebopDroneDecodeStream$ make
/usr/bin/ld: //usr/local/lib/libavcodec.a(pthread_frame.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [BebopDroneDecodeStream] Error 1

What do I have to do ? 
Best, Alex

**Comment by vbr74** [comment]
Hi, These error is due to an unlinked library : pthread, I have a lots of dependencies errors too with the SDK , this is my EXTERNAL_LIBS MakeFile input :

 EXTERNAL_LIB=-lncurses -lavcodec -lavformat -lswscale -lavutil -lpthread -lm -lz -lrt -ldl -lswresample

PS : I've just added some others libraires like math one due to other dependencies errors.

Greetings,
Valentin.

**Comment by alexcherpi** [comment]
Thanks it worked!

**Comment by vbr74** [comment]
You're welcome, but have you already tried to connect to ? Because I suppose (but i'm not sure) that is it not possible to initiate a remote control session with the bebop if you're computer isn't equiped with a Wifi Card, because I've tried it with a Development PC connected via an ethernet Switch to my personal laptop which make packet routing between the Bebop (192.168.42.1/24) with my PC (192.168.0.41/24), the "laptop router" use nating.

So, after succesful ping with the bebop from my PC, when I lauch the compiled sample, all of my terminal's input became dark and after 10 seconds, the PC get timeout. TCP packet with port 4444 works great but when the software initiate an UDP Stream with the Bebop there are no response from it.

Does anyone get a similar problem ?
Greetings, Valentin.

**Comment by alexcherpi** [comment]
Heuuuum I only tested with a computer which has a wifi card. Sorry..

**Comment by vbr74** [comment]
So I confirm, you cannot execute the build on a computer which has no wireless direct connection to the bebop, the only exception is if you have virtualbox installed and you run the build with a wifi card on bridge mode inside a VM.
